name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate-changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate changelog
        id: git-cliff
        uses: orhun/git-cliff-action@v2
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGELOG.md

  release:
    name: Build & Release
    runs-on: ubuntu-latest
    needs: generate-changelog
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build Artifact
        uses: actions-rs/cargo@v1
        id: build-artifact
        with:
          command: build
          args: --release --locked
      - name: Upload Artifact
        uses: svenstaro/upload-release-action@v2
        with:
          file: target/release/metamask-bruteforce
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true
          release_name: "Release ${{ github.ref_name }}"
          body: "${{ needs.generate-changelog.outputs.release_body }}"
